#!/bin/sh

if [ $# -lt 1 ] ; then
  echo "USAGE: $0 appname"
  echo " e.g.: $0 mtop"
  exit 1;
fi

CONFIG=/opt/@Work/scripts/sshc_config

SOURCE=$0
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
WORKDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ ! -f $CONFIG/app_$1.conf -o "$2" = "refresh" ];then
    echo "create $1 appconfig!"
    pesystem -n $1 -t tmhost > $CONFIG/app_$1.conf
fi

sshc -c $CONFIG/app_$1.conf

