#!/bin/sh

PROG=`basename $0`
USAGE="Usage: $PROG <host> <asuser> <localfile> <remotedir>

EXAMPLES:
  $PROG 1.2.3.4  admin /home/admin/foo/httpd.conf /home/admin/cai/etc
"

cd `dirname $0`
BASE_HOME=$PWD
if [ -L $0 ] ; then
    FILE=`readlink $0`
    BASE_HOME=$BASE_HOME/`dirname $FILE`
    cd $BASE_HOME
fi

if [ $# -lt 4 ];then
 echo "$USAGE"
 exit 1
fi

HOST=$1
ASUSER=$2
LOCALFILE=$3
REMOTEDIR=$4

$BASE_HOME/npscp $LOCALFILE $HOST:/tmp/
$BASE_HOME/npsshc $HOST "sudo -u $ASUSER -H cp /tmp/`basename $LOCALFILE` $REMOTEDIR"
