#!/usr/bin/expect -f
# Script to supply root/admin password for remote ssh server
#
# author xinshi@taobao.com
#
source [file dirname [info script]]/explib/initEnv.exp

set USAGE "Usage: $argv0 host cmd\n\n"

if { $argc < 2 } {
   send_user $USAGE
   exit
}

set timeout 300
spawn -noecho tboard -u$username
#log_user 0
#exp_internal 1
set DONE 0
expect {
                     "connecting (yes/no)?" {
                         send "yes\r"
                         exp_continue
                     } "word:" {
                         send "$password\r"
												 exp_continue
		     						 } "~]$ " {
												 if { $DONE == 1 } {
													 exit
												 } else {
														send -- "ssh -t [lindex $argv 0] \"[lindex $argv 1]\"\r"
														set DONE 1
													  exp_continue
												 }
										 }
                 }

