#!/usr/bin/expect -f
# Script to supply root/admin password for remote ssh server
#
# author xinshi@taobao.com
#
source [file dirname [info script]]/explib/initEnv.exp

set timeout 300
#log_user 0
#exp_internal 1
spawn -noecho ssh [lindex $argv 0]
expect {
                     "connecting (yes/no)?" {
                         send "yes\r"
                         exp_continue
                     } "word:" {
                         send "$password\r"
			 interact
		    }  "~]$ " {
			 interact
                    } eof { 
			exit 
                    } 
                    
                 }
